/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arifs
 */
public class MenuBar extends javax.swing.JFrame {

    /**
     * Creates new form MenuBar
     */
    public MenuBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MnuMaster = new javax.swing.JMenu();
        MnuDataBrg = new javax.swing.JMenuItem();
        MnuDataPlg = new javax.swing.JMenuItem();
        MnuKelompok = new javax.swing.JMenuItem();
        MnuSubKelompok = new javax.swing.JCheckBoxMenuItem();
        MnuPemasok = new javax.swing.JMenuItem();
        MnuStatus = new javax.swing.JMenu();
        MnuStatusPnj = new javax.swing.JCheckBoxMenuItem();
        MnuStatusPmb = new javax.swing.JCheckBoxMenuItem();
        MnuStatusTrans = new javax.swing.JMenu();
        MnuPenjualan = new javax.swing.JMenuItem();
        MnuPembelian = new javax.swing.JMenuItem();
        MnuCetakTrans = new javax.swing.JMenu();
        MnuCetakPnj = new javax.swing.JCheckBoxMenuItem();
        MnuCetakPmb = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Design Preview [ Frame Menu ]");

        MnuMaster.setText("Master");

        MnuDataBrg.setText("Data Barang");
        MnuMaster.add(MnuDataBrg);

        MnuDataPlg.setText("Data Pelanggan");
        MnuMaster.add(MnuDataPlg);

        MnuKelompok.setText("Kelompok");
        MnuMaster.add(MnuKelompok);

        MnuSubKelompok.setSelected(true);
        MnuSubKelompok.setText("Sub Kelompok");
        MnuMaster.add(MnuSubKelompok);

        MnuPemasok.setText("Data Pemasok");
        MnuMaster.add(MnuPemasok);

        MnuStatus.setText("Status");

        MnuStatusPnj.setSelected(true);
        MnuStatusPnj.setText("Penjualan");
        MnuStatus.add(MnuStatusPnj);

        MnuStatusPmb.setSelected(true);
        MnuStatusPmb.setText("Pembelian");
        MnuStatus.add(MnuStatusPmb);

        MnuMaster.add(MnuStatus);

        jMenuBar1.add(MnuMaster);

        MnuStatusTrans.setText("Transaksi");

        MnuPenjualan.setText("Penjualan");
        MnuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuPenjualanActionPerformed(evt);
            }
        });
        MnuStatusTrans.add(MnuPenjualan);

        MnuPembelian.setText("Pembelian");
        MnuStatusTrans.add(MnuPembelian);

        MnuCetakTrans.setText("Cetak Transaksi");

        MnuCetakPnj.setSelected(true);
        MnuCetakPnj.setText("Penjualan");
        MnuCetakTrans.add(MnuCetakPnj);

        MnuCetakPmb.setSelected(true);
        MnuCetakPmb.setText("Pembelian");
        MnuCetakTrans.add(MnuCetakPmb);

        MnuStatusTrans.add(MnuCetakTrans);

        jMenuBar1.add(MnuStatusTrans);

        jMenu1.setText("Laporan");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Utility");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuPenjualanActionPerformed
        // TODO add your handling code here:
        FormTransPenjualan FormJual = new FormTransPenjualan();
        FormJual.setLocationRelativeTo(FormJual);
        FormJual.setVisible(true);
    }//GEN-LAST:event_MnuPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem MnuCetakPmb;
    private javax.swing.JCheckBoxMenuItem MnuCetakPnj;
    private javax.swing.JMenu MnuCetakTrans;
    private javax.swing.JMenuItem MnuDataBrg;
    private javax.swing.JMenuItem MnuDataPlg;
    private javax.swing.JMenuItem MnuKelompok;
    private javax.swing.JMenu MnuMaster;
    private javax.swing.JMenuItem MnuPemasok;
    private javax.swing.JMenuItem MnuPembelian;
    private javax.swing.JMenuItem MnuPenjualan;
    private javax.swing.JMenu MnuStatus;
    private javax.swing.JCheckBoxMenuItem MnuStatusPmb;
    private javax.swing.JCheckBoxMenuItem MnuStatusPnj;
    private javax.swing.JMenu MnuStatusTrans;
    private javax.swing.JCheckBoxMenuItem MnuSubKelompok;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
