/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasiemployee;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arifs
 */
public class DaftarPekerja extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection conn = aplikasiemployee.DBConnection.Connect();

    /**
     * Creates new form DaftarPekerja
     */
    public DaftarPekerja() {
        initComponents();
        title();
        showData("");
        
        delBtn.setEnabled(false);
        SaveBtn.setEnabled(false);
        inputId.setEnabled(false);
        inputFirstname.setEnabled(false);
        inputLastname.setEnabled(false);
        inputJobtitle.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        idLabel = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        firstnameLabel = new javax.swing.JLabel();
        inputFirstname = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        inputLastname = new javax.swing.JTextField();
        jobtitleLabel = new javax.swing.JLabel();
        inputJobtitle = new javax.swing.JTextField();
        delBtn = new javax.swing.JButton();
        newBtn = new javax.swing.JButton();
        refBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableView.setShowGrid(true);
        tableView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableView);

        idLabel.setText("Id:");

        inputId.setActionCommand("<Not Set>");
        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });

        firstnameLabel.setText("Firstname");

        lastnameLabel.setText("Lastname");

        jobtitleLabel.setText("Jobtitle");

        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        newBtn.setText("New");
        newBtn.setToolTipText("");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        refBtn.setText("Refresh");
        refBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refBtnActionPerformed(evt);
            }
        });

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newBtn)
                .addGap(33, 33, 33)
                .addComponent(delBtn)
                .addGap(32, 32, 32)
                .addComponent(refBtn)
                .addGap(36, 36, 36)
                .addComponent(SaveBtn)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jobtitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(inputJobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastnameLabel)
                            .addComponent(firstnameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputLastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputFirstname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel)
                    .addComponent(inputFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel)
                    .addComponent(inputLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobtitleLabel)
                    .addComponent(inputJobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBtn)
                    .addComponent(delBtn)
                    .addComponent(refBtn)
                    .addComponent(SaveBtn))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        // TODO add your handling code here:
        SaveBtn.setEnabled(true);
        inputId.setEnabled(true);
        inputFirstname.setEnabled(true);
        inputLastname.setEnabled(true);
        inputJobtitle.setEnabled(true);
        newBtn.setEnabled(false);
    }//GEN-LAST:event_newBtnActionPerformed

    private void refBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refBtnActionPerformed
        // TODO add your handling code here:
        newBtn.setEnabled(true);
        SaveBtn.setEnabled(false);
        inputId.setEnabled(false);
        inputId.setText("");
        inputFirstname.setEnabled(false);
        inputFirstname.setText("");
        inputLastname.setEnabled(false);
        inputLastname.setText("");
        inputJobtitle.setEnabled(false);
        inputJobtitle.setText("");
    }//GEN-LAST:event_refBtnActionPerformed

    private void tableViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableViewMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Row Column Clicked");
        int row = tableView.getSelectedRow();
        int col = tableView.getSelectedColumn();
        Object [] selected = (Object[]) tableView.getValueAt(row, col);
//        tableView.getValueAt(row);
        JOptionPane.showMessageDialog(null, " data is "  );
        delBtn.setEnabled(true);
        SaveBtn.setEnabled(false);
        newBtn.setEnabled(false);
        refBtn.setEnabled(false);
    }//GEN-LAST:event_tableViewMouseClicked

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        try{
            st = conn.createStatement();
            st.executeUpdate("INSERT INTO workers VALUES('" +inputId.getText()+"','"
                    + inputFirstname.getText() + "','"
                    + inputLastname.getText() + "','"
                    + inputJobtitle.getText() + "')"
            );
            showData("");
            JOptionPane.showMessageDialog(null, "Data Saved!");
            newBtn.setEnabled(true);
            SaveBtn.setEnabled(false);
            inputId.setEnabled(false);
            inputId.setText("");
            inputFirstname.setEnabled(false);
            inputFirstname.setText("");
            inputLastname.setEnabled(false);
            inputLastname.setText("");
            inputJobtitle.setEnabled(false);
            inputJobtitle.setText("");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    public final void title() {
        Object[] title = {
                "Id", "First Name", "Last Name", "Job Title"
        };
        tabModel = new DefaultTableModel(null, title);
        tableView.setModel(tabModel);
    }
    
    public final void showData(String where) {
        try {
            st = conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM workers "+ where);
            
            while (rs.next()){
                Object[] data = {
                    rs.getString("id"),
                    rs.getString("First_Name"),
                    rs.getString("Last_Name"),
                    rs.getString("Job_Title")
                };
                tabModel.addRow(data);
            }
//            tableView.app
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarPekerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarPekerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarPekerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarPekerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarPekerja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField inputFirstname;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputJobtitle;
    private javax.swing.JTextField inputLastname;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jobtitleLabel;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JButton newBtn;
    private javax.swing.JButton refBtn;
    private javax.swing.JTable tableView;
    // End of variables declaration//GEN-END:variables
}
