/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkbox;

/**
 *
 * @author arifs
 */
public class GroupButton_Arif_Suwadji extends javax.swing.JFrame {

    /**
     * Creates new form GroupButton_Arif_Suwadji
     */
    public GroupButton_Arif_Suwadji() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        CreditCardRadio = new javax.swing.JRadioButton();
        DebitCardRadio = new javax.swing.JRadioButton();
        PaypalRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        CardView = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreditCardRadio.setText("Credit Card");
        CreditCardRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditCardRadioActionPerformed(evt);
            }
        });

        DebitCardRadio.setText("Debit Card");
        DebitCardRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitCardRadioActionPerformed(evt);
            }
        });

        PaypalRadio.setText("Pay Pal");
        PaypalRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaypalRadioActionPerformed(evt);
            }
        });

        jLabel1.setText("Sistem Pembayaran");

        CardView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)
                        .addComponent(CardView, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CreditCardRadio)
                        .addComponent(DebitCardRadio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PaypalRadio, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(CreditCardRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DebitCardRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PaypalRadio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(CardView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CardViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardViewActionPerformed

    private void CreditCardRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditCardRadioActionPerformed
        // TODO add your handling code here:
        CardView.setText(CreditCardRadio.getText());
    }//GEN-LAST:event_CreditCardRadioActionPerformed

    private void DebitCardRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitCardRadioActionPerformed
        // TODO add your handling code here:
        CardView.setText(DebitCardRadio.getText());
    }//GEN-LAST:event_DebitCardRadioActionPerformed

    private void PaypalRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaypalRadioActionPerformed
        // TODO add your handling code here:
        CardView.setText(PaypalRadio.getText());
    }//GEN-LAST:event_PaypalRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupButton_Arif_Suwadji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupButton_Arif_Suwadji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupButton_Arif_Suwadji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupButton_Arif_Suwadji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupButton_Arif_Suwadji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CardView;
    private javax.swing.JRadioButton CreditCardRadio;
    private javax.swing.JRadioButton DebitCardRadio;
    private javax.swing.JRadioButton PaypalRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
