/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts.pbo.temperatur;

import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author arifs
 */
public class temperatur extends javax.swing.JFrame {

    /**
     * Creates new form temperatur
     */
    public temperatur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FLabel = new javax.swing.JLabel();
        FTextField = new javax.swing.JTextField();
        colorPanel = new javax.swing.JPanel();
        temperatureScrollBar = new javax.swing.JScrollBar();
        CLabel = new javax.swing.JLabel();
        CTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Conversion");
        setAlwaysOnTop(true);
        setResizable(false);

        FLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FLabel.setText("Farenheit");

        FTextField.setEditable(false);
        FTextField.setBackground(new java.awt.Color(255, 255, 255));
        FTextField.setColumns(10);
        FTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FTextField.setText("32.0");

        colorPanel.setBackground(java.awt.Color.blue);
        colorPanel.setToolTipText("");
        colorPanel.setPreferredSize(new java.awt.Dimension(280, 40));
        colorPanel.setVerifyInputWhenFocusTarget(false);

        temperatureScrollBar.setMaximum(1200);
        temperatureScrollBar.setMinimum(-600);
        temperatureScrollBar.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        temperatureScrollBar.setValue(320);
        temperatureScrollBar.setPreferredSize(new java.awt.Dimension(200, 30));
        temperatureScrollBar.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                temperatureScrollBarAdjustmentValueChanged(evt);
            }
        });

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(temperatureScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(temperatureScrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        CLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CLabel.setText("Celcius");

        CTextField.setEditable(false);
        CTextField.setBackground(new java.awt.Color(255, 255, 255));
        CTextField.setColumns(10);
        CTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CTextField.setText("0.0");
        CTextField.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(FLabel)
                        .addGap(28, 28, 28)
                        .addComponent(FTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(CLabel)
                        .addGap(44, 44, 44)
                        .addComponent(CTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FLabel)
                    .addComponent(FTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(colorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CLabel)
                    .addComponent(CTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temperatureScrollBarAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_temperatureScrollBarAdjustmentValueChanged
        // TODO add your handling code here:
        Double tempF = (double) temperatureScrollBar.getValue() / 10;
        if(tempF >= 70){
            colorPanel.setBackground(Color.RED);
            Konversi();
        }else {
            colorPanel.setBackground(Color.BLUE);
            Konversi();
        }
        
    }//GEN-LAST:event_temperatureScrollBarAdjustmentValueChanged

    public void Konversi(){
        Double tempF = (double) temperatureScrollBar.getValue() / 10;
        FTextField.setText(new DecimalFormat("0.0").format(tempF));
        Double tempC = (tempF - 32.0) * 5.0 / 9.0;
        CTextField.setText(new DecimalFormat("0.0").format(tempC));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(temperatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(temperatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(temperatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(temperatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new temperatur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLabel;
    private javax.swing.JTextField CTextField;
    private javax.swing.JLabel FLabel;
    private javax.swing.JTextField FTextField;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JScrollBar temperatureScrollBar;
    // End of variables declaration//GEN-END:variables
}
